=== SymbianSource/oss.FCL.sftools.dev.build/buildframework/helium/tools/common/schema/helium_data_model.xsd
<?xml version="1.0" encoding="UTF-8"?><!--W3C Schema generated by XMLSPY v2004 rel. 3 U (http://www.xmlspy.com)--><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">    <xs:element name="description" type="xs:string"/>    <xs:element name="deprecated" type="xs:string"/>    <xs:element name="enumeration">        <xs:complexType>            <xs:attribute name="value" use="required">                <xs:simpleType>                    <xs:restriction base="xs:NMTOKEN">                        <xs:enumeration value="ebs"/>                        <xs:enumeration value="ec"/>                    </xs:restriction>                </xs:simpleType>            </xs:attribute>        </xs:complexType>    </xs:element>    <xs:element name="group">        <xs:complexType>            <xs:sequence>                <xs:element ref="name"/>                <xs:element ref="description"/>                <xs:element ref="propertyRef" maxOccurs="unbounded"/>            </xs:sequence>        </xs:complexType>    </xs:element>    <xs:element name="heliumDataModel">        <xs:complexType>            <xs:sequence>                <xs:element ref="property" maxOccurs="unbounded"/>                <xs:element ref="group" maxOccurs="unbounded"/>            </xs:sequence>        </xs:complexType>    </xs:element>    <xs:element name="name" type="xs:string"/>    <xs:element name="property">        <xs:complexType>            <xs:choice maxOccurs="unbounded">                <xs:element ref="name"/>                <xs:element ref="usage" minOccurs="0"/>                <xs:element ref="type" minOccurs="0"/>                <xs:element name="editStatus">                    <xs:simpleType>                        <xs:restriction base="xs:string">                            <xs:enumeration value="must"/>                            <xs:enumeration value="recommended"/>                            <xs:enumeration value="allowed"/>                            <xs:enumeration value="discouraged"/>                            <xs:enumeration value="never"/>                        </xs:restriction>                    </xs:simpleType>                </xs:element>                <xs:element ref="description"/>                <xs:element ref="deprecated" minOccurs="0"/>            </xs:choice>        </xs:complexType>    </xs:element>    <xs:element name="propertyRef">        <xs:complexType>            <xs:simpleContent>                <xs:extension base="xs:string">                    <xs:attribute name="usage" use="required">                        <xs:simpleType>                            <xs:restriction base="xs:NMTOKEN">                                <xs:enumeration value="optional"/>                                <xs:enumeration value="required"/>                            </xs:restriction>                        </xs:simpleType>                    </xs:attribute>                </xs:extension>            </xs:simpleContent>        </xs:complexType>    </xs:element>    <xs:element name="restriction">        <xs:complexType>            <xs:sequence>                <xs:element ref="enumeration" maxOccurs="unbounded"/>            </xs:sequence>            <xs:attribute name="base" type="xs:QName" use="required"/>        </xs:complexType>    </xs:element>    <xs:element name="type">        <xs:complexType mixed="true">            <xs:choice minOccurs="0" maxOccurs="unbounded">                <xs:element ref="restriction"/>            </xs:choice>        </xs:complexType>    </xs:element>    <xs:element name="usage">        <xs:simpleType>            <xs:restriction base="xs:string">                <xs:enumeration value="optional"/>                <xs:enumeration value="required"/>            </xs:restriction>        </xs:simpleType>    </xs:element></xs:schema>

=== SymbianSource/oss.FCL.sftools.dev.build/buildframework/helium/config/helium_data_model.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
============================================================================ 
Name        : helium_data_model.xml 
Part of     : Helium 

Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
All rights reserved.
This component and the accompanying materials are made available
under the terms of the License "Eclipse Public License v1.0"
which accompanies this distribution, and is available
at the URL "http://www.eclipse.org/legal/epl-v10.html".

Initial Contributors:
Nokia Corporation - initial contribution.

Contributors:

Description:

============================================================================
-->
<!--

This describes the allowed values for some of the fields:

property:
- editStatus: [must, recommended, allowed, discouraged, never] 
  type: [string, boolean, integer]

-->
<heliumDataModel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\tools\common\schema\helium_data_model.xsd">
    <property>
        <name>archive.max.number.of.threads</name>
        <editStatus>allowed</editStatus>
        <type>integer</type>
        <description>Set the maximum number of threads running for archiving (for a parallel job).</description>
    </property>
    <property>
        <name>ats.ctc.host</name>
        <editStatus>recommended</editStatus>
        <type>string</type>
        <description>CTC host, provided by CATS used to create coverage measurement reports. MON.sym files are copied to this location, for example "10.0.0.1". If not given, code coverage reports are not created</description>
    </property>
    <property>
        <name>ats.testrun.name</name>
        <editStatus>recommended</editStatus>
        <type>string</type>
        <description>Modify the test-run name if you have understanding of test.xml file or leave it as it is. Default value is a string consist of build id, product name, major and minor versions</description>
    </property>
    <property>
        <name>ats.plan.name</name>
        <editStatus>recommended</editStatus>
        <type>string</type>
        <description>Modify the plan name if you have understanding of test.xml file or leave it as it is. Default value is "plan" </description>
    </property>
    <property>
        <name>ats.trace.enabled</name>
        <editStatus>recommended</editStatus>
        <type>string</type>
        <description>Should be "True" if tracing is needed during the tests running on ATS3. Default value is "False", the values are case-sensitive. </description>
    </property>
    <property>
        <name>ats.ctc.enabled</name>
        <editStatus>recommended</editStatus>
        <type>string</type>
        <description>Should be "True" if coverage measurement and dynamic analysis (CTC) tool support is to be used by ATS. Default value is "False", the values are case-sensitive. </description>
    </property>
    <property>
        <name>ats.email.list</name>
        <editStatus>recommended</editStatus>
        <type>string</type>
        <description>The property is needed if you want to get an email from ATS server after the tests are executed. There can be one to many semicolon(s) ";" separated email addresses.</description>
    </property>
    <property>
        <name>ats.aste.email.list</name>
        <editStatus>recommended</editStatus>
        <type>string</type>
        <description>The property is needed if you want to get an email from ATS server after the tests are executed. There can be one to many semicolon(s) ";" separated email addresses.</description>
    </property>
    <property>
        <name>ats.flashfiles.minlimit</name>
        <editStatus>recommended</editStatus>
        <type>string</type>
        <description>Limit of minimum number of flash files to execute ats-test target, otherwise ATSDrop.zip will not be generated. Default value is "2" files.</description>
    </property>
    <property>
        <name>ats.sisfiles.minlimit</name>
        <editStatus>recommended</editStatus>
        <type>string</type>
        <description>Limit of minimum number of sis files to execute matti-test target, otherwise MATTI-drop.zip will not be generated. Default value is "1" files.</description>
    </property>
    <property>
        <name>ats.target.platform</name>
        <editStatus>recommended</editStatus>
        <type>string</type>
        <description>Sets target platform for compiling test components. Default value is "armv5 urel".</description>
    </property>
    <property>
        <name>ats.test.timeout</name>
        <editStatus>recommended</editStatus>
        <type>string</type>
        <description>To set test commands execution time limit on ATS3 server, in seconds. Default value is "60".</description>
    </property>
    <property>
        <name>ats.product.hwid</name>
        <editStatus>recommended</editStatus>
        <type>string</type>
        <description>Product HardWare ID (HWID) attached to ATS. By default the value of HWID is not set.</description>
    </property>
    <property>
        <name>ats.obey.pkgfiles.rule</name>
        <editStatus>recommended</editStatus>
        <type>string</type>
        <description>If the property is set to "True", then the only test components which will have PKG files, will be included into the test.xml as a test-set. Which means, even if there's a test component (executable) but there's no PKG file, it should not be considered as a test component and hence not included into the test.xml as a separate test. By default the property value is False.</description>
    </property>
    <property>
        <name>tsrc.data.dir</name>
        <editStatus>allowed</editStatus>
        <type>string</type>
        <description>The default value is "data" and refers to the 'data' directory under 'tsrc' directory.</description>
    </property>
    <property>
        <name>tsrc.path.list</name>
        <editStatus>allowed</editStatus>
        <type>string</type>
        <description>Contains list of the tsrc directories. Gets the list from system definition layer files. Assuming that the test components are defined already in te layers.sysdef.xml files to get compiled. 
        Not recommended, but the property value can be set if there are no system definition file(s), and tsrc directories paths to set manually.</description>
    </property>
    <property>
        <name>ats.flash.images</name>
        <editStatus>allowed</editStatus>
        <type>string</type>
        <description>List of flash images (.fpsx files) to install on the phone. It is not recommended to set the value manually however, it is possible.</description>
    </property>
    <property>
        <name>ats.report.location</name>
        <editStatus>allowed</editStatus>
        <type>string</type>
        <description>Sets ATS reports store location. Default location is "${publish.dir}/${publish.subdir}"</description>
    </property>
    <property>
        <name>ats.drop.file</name>
        <editStatus>discouraged</editStatus>
        <type>string</type>
        <description>Path for creation of the drop file during the build. Default is ATS3Drop.zip</description>
    </property>
    <property>
        <name>ats.aste.drop.file</name>
        <editStatus>discouraged</editStatus>
        <type>string</type>
        <description>Path for creation of the drop file during the build. Default is ATS3AsteDrop.zip</description>
    </property>
    <property>
        <name>ats.drops.count</name>
        <editStatus>discouraged</editStatus>
        <type>string</type>
        <description>ATSDrop files counter. Value is set to have total number of ATSDrops.</description>
    </property>
    <property>
        <name>ats.product.name</name>
        <editStatus>must</editStatus>
        <type>string</type>
        <description>Name of the product to be tested. For example: "PRODUCT"</description>
    </property>
    <property>
        <name>ats.script.type</name>
        <editStatus>recommended</editStatus>
        <type>string</type>
        <description>There are two types of ats script files to send drop to ATS server, "runx" and "import"; 
        only difference is that with "import" ATS doesn't have to have access rights to testdrop.zip file, 
        as it is sent to the system over http and import doesn't need network shares. 
        If that is not needed "import" should not be used. Default value is "runx" as "import" involves heavy processing on ATS server</description>
    </property>
    <property>
        <name>ats.drop.location</name>
        <editStatus>must</editStatus>
        <type>string</type>
        <description>Server location (UNC path) to save the ATS3Drop file, before sending to the ATS. For example: \\trwsem00\some_folder\. In case, ``ats.script.type`` is set to "import", ATS doesn't need to have access to ats.drop.location,  its value can be any local folder on build machine, for example c:\temp (no network share needed).</description>
    </property>
    <property>
        <name>ats.aste.testrun.name</name>
        <editStatus>recommended</editStatus>
        <type>string</type>
        <description>Modify the test-run name if you have understanding of test.xml file or leave it as it is. Default value is a string consist of build id, product name, major and minor versions</description>
    </property>
    <property>
        <name>ats.aste.plan.name</name>
        <editStatus>recommended</editStatus>
        <type>string</type>
        <description>Modify the plan name if you have understanding of test.xml file or leave it as it is. Default value is "plan" </description>
    </property>
    <property>
        <name>ats.evalid.pre</name>
        <editStatus>never</editStatus>
        <type>string</type>
