=== SymbianSource/oss.FCL.sftools.dev.build/sbsv2/raptor/schema/build/2_0.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://symbian.com/xml/build" targetNamespace="http://symbian.com/xml/build" elementFormDefault="qualified">
	<xsd:annotation>
		<xsd:documentation xml:lang="en">
			Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
			All rights reserved.
			This component and the accompanying materials are made available
			under the terms of the License "Eclipse Public License v1.0"
			which accompanies this distribution, and is available
			at the URL "http://www.eclipse.org/legal/epl-v10.html".

			Initial Contributors:
			Nokia Corporation - initial contribution.

			Contributors:

			Description:

		</xsd:documentation>
	</xsd:annotation>
	<xsd:element name="build">
		<xsd:complexType>
			<xsd:sequence maxOccurs="unbounded">
				<xsd:element ref="var" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="alias" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="group" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="interface" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="var">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:sequence minOccurs="0">
					<xsd:element ref="varRef" minOccurs="0" maxOccurs="unbounded"/>
				</xsd:sequence>
				<xsd:sequence maxOccurs="unbounded">
					<xsd:element name="env" minOccurs="0" maxOccurs="unbounded">
						<xsd:complexType>
							<xsd:attribute name="name" type="xsd:string" use="required"/>
							<xsd:attribute name="default" type="xsd:string" use="optional"/>
							<xsd:attribute name="type" type="xsd:string"/>
							<xsd:attribute name="versionCommand" type="xsd:string"/>
							<xsd:attribute name="versionResult" type="xsd:string"/>
						</xsd:complexType>
					</xsd:element>
					<xsd:element name="set" minOccurs="0" maxOccurs="unbounded">
						<xsd:complexType>
							<xsd:attribute name="name" type="xsd:string" use="required"/>
							<xsd:attribute name="value" type="xsd:string" use="required"/>
							<xsd:attribute name="type" type="xsd:string"/>
							<xsd:attribute name="versionCommand" type="xsd:string"/>
							<xsd:attribute name="versionResult" type="xsd:string"/>
							<xsd:attribute name="host" type="xsd:string"/>
						</xsd:complexType>
					</xsd:element>
					<xsd:element name="append" minOccurs="0" maxOccurs="unbounded">
						<xsd:complexType>
							<xsd:attribute name="name" type="xsd:string" use="required"/>
							<xsd:attribute name="value" type="xsd:string" use="required"/>
							<xsd:attribute name="separator" type="xsd:string"/>
						</xsd:complexType>
					</xsd:element>
					<xsd:element name="prepend" minOccurs="0" maxOccurs="unbounded">
						<xsd:complexType>
							<xsd:attribute name="name" type="xsd:string" use="required"/>
							<xsd:attribute name="value" type="xsd:string" use="required"/>
							<xsd:attribute name="separator" type="xsd:string"/>
						</xsd:complexType>
					</xsd:element>
				</xsd:sequence>
			</xsd:sequence>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="extends" type="xsd:string"/>
			<xsd:attribute name="host" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="alias">
		<xsd:complexType>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="meaning" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="group">
		<xsd:complexType>
			<xsd:sequence maxOccurs="unbounded">
				<xsd:element ref="varRef" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="aliasRef" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="groupRef" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="name" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="varRef">
		<xsd:complexType>
			<xsd:attribute name="ref" type="xsd:string" use="required"/>
			<xsd:attribute name="mod" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="aliasRef">
		<xsd:complexType>
			<xsd:attribute name="ref" type="xsd:string" use="required"/>
			<xsd:attribute name="mod" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="groupRef">
		<xsd:complexType>
			<xsd:attribute name="ref" type="xsd:string" use="required"/>
			<xsd:attribute name="mod" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="interface">
		<xsd:complexType>
			<xsd:sequence minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="param" minOccurs="0" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:attribute name="name" type="xsd:string" use="required"/>
						<xsd:attribute name="default" type="xsd:string"/>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="paramgroup" minOccurs="0" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:attribute name="pattern" type="xsd:string" use="required"/>
						<xsd:attribute name="default" type="xsd:string"/>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="extends" type="xsd:string"/>
			<xsd:attribute name="abstract" type="xsd:boolean"/>
			<xsd:attribute name="flm" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== SymbianSource/oss.FCL.sftools.dev.build/sbsv2/raptor/test/config/arm.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<build xmlns="http://symbian.com/xml/build"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://symbian.com/xml/build build/2_0.xsd">

  <!-- build configurations for ARM compilers -->

  <var name="ARMV5_BASE">
    <env name='SBS_HOME' default='' type='path'/>
    <env name='EPOCROOT'/>
    <env name='ARMROOT'/>

    <set name='FLMHOME' value='$(SBS_HOME)/lib/flm'/>
    <set name='TRADITIONAL_PLATFORM' value='ARMV5'/>
    <set name='VARIANT_CFG' value='$(EPOCROOT)/variant/variant.cfg'/>
  </var>

  <var name="ARMV5_UDEB" extends="ARMV5_BASE">
    <append name='ABC' value='abc' />
    <append name='VARIANT_CFG' value='2' separator='' />
  </var>

  <var name="ARMV5_UREL" extends="ARMV5_BASE">
    <prepend name='ABC' value='abc' />
    <prepend name='VARIANT_CFG' value='' separator='' />
  </var>

  <var name="MOD1">
    <set name="X" value="X1"/>
  </var>

  <var name="MOD2">
    <set name="X" value="X2"/>
    <set name="Y" value="Y2"/>
  </var>

  <group name="ARMV5">
    <varRef ref="ARMV5_UREL"/>
    <varRef ref="ARMV5_UDEB"/>
  </group>

  <alias name="ALIAS_1" meaning="ARMV5_UREL.MOD1"/>
  <alias name="ALIAS_2" meaning="ARMV5_UDEB.MOD1.MOD2"/>

  <group name="G1">
    <varRef ref="MOD1"/>
    <varRef ref="MOD2"/>
  </group>

  <group name="G2">
    <varRef ref="ARMV5_UREL" mod="MOD1"/>
    <varRef ref="ARMV5_UDEB" mod="MOD1.MOD2"/>
    <aliasRef ref="ALIAS_1"/>
    <aliasRef ref="ALIAS_2" mod="MOD1.MOD2.MOD1"/>
    <groupRef ref="ARMV5" mod="MOD2"/>
    <groupRef ref="G1"/>
  </group>

  <!-- these are deliberately redefined in user.xml -->
  
  <alias name="alias_redef" meaning="MOD1"/>
  <group name="group_redef"><varRef ref="MOD1"/></group>
  <interface name="interface_redef" abstract="true"/>
  <var name="var_redef"></var>
  
</build>

=== SymbianSource/oss.FCL.sftools.dev.build/deprecated/buildtools/buildsystem/extension/base/bootstrap.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<build xmlns="http://symbian.com/xml/build" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://symbian.com/xml/build build/2_0.xsd">

<!-- Extension interfaces : replacements for Template Extension Makefiles 
-->

<interface name="base.bootstrap" extends="Symbian.KernelFLM" flm="bootstrap.flm">
		<param name="E32PATH" />
		<param name="NAME" />
		<param name="MEMMODEL" />
		<param name="EXTRA_INC_PATH" default=''/>
		<param name="EXTRA_EPOC32_INC_PATH" default=''/>
		<param name="SOURCES" />
		<param name="INCLUDES" />
		<param name="ASM_MACROS" default='' />
		<param name="GENINCLUDES_HEADERS" default=''/>
		<param name="CPU" default='arm'/>
		<param name="SMP" default=''/>
		<param name="LINKBASE" default='0x00000000'/>
		<param name="BASESOURCES_NAMES" default="bootmain.s bootcpu.s bootutils.s"/>
		<param name="INC_PATH" default=''/>
	</interface>
</build>

=== SymbianSource/oss.FCL.sftools.dev.build/sbsv2/raptor/lib/flm/msvctools.xml
<?xml version='1.0' encoding='ISO-8859-1'?>
<build xmlns='http://symbian.com/xml/build' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation='http://symbian.com/xml/build ../../schema/build/2_0.xsd'>
	<!-- Tools interfaces -->

	<interface name='msvctools.flm' extends='base.flm' abstract='true'>
		<param name='INSTALLPATH'/>
		<param name='IMPORTLIBPATH'/>
		<param name='OUTPUTPATH'/>
		<param name='VARIANTPLATFORM'/>
		<param name='PLATFORM' default='$(VARIANTPLATFORM)'/>
		<param name='PRODUCT_INCLUDE'/>
		<param name='RELEASEPATHROOT'/>
		<param name='REQUESTEDTARGETEXT' default=''/>
		<param name='VARIANTTYPE'/>
		<param name='FULLVARIANTPATH'/>
		<param name='PLATMACROS.WINDOWS'/>
		<param name='PLATMACROS.LINUX'/>
	</interface>

	<interface name='msvctools.mmp' extends='msvctools.flm' abstract='true'>
		<param name='LIBRARY' default=''/>
		<param name='OPTION_MSVC' default=''/>
		<param name='SOURCE' default=''/>
		<param name='STATICLIBRARY' default=''/>
		<param name='SYSTEMINCLUDE' default=''/>
		<param name='TARGET'/>
		<param name='TARGETPATH'/>
		<param name='TARGETTYPE'/>
		<param name='USERINCLUDE' default=''/>
		<param name='WIN32_HEADERS' default=''/>
		<param name='WIN32_LIBRARY' default=''/>
	</interface>

	<interface name='msvctools.toolchain' extends='msvctools.mmp' abstract='true'>
		<param name='INCLUDE'/>
		<param name='LIB'/>
		<param name='OPT.BROWSEDB'/>
		<param name='OPT.BROWSEFILE'/>
		<param name='OPT.COMPILE'/>
		<param name='OPT.DEFINE'/>
		<param name='OPT.INCLUDE'/>
		<param name='OPT.LISTING'/>
		<param name='OPT.OBJECTFILE'/>
		<param name='OPT.OUTFILE'/>
		<param name='OPT.PREINCLUDE'/>
		<param name='OPT.SUBSYSTEM'/>
		<param name='OPT.SYSINCLUDE'/>
		<param name='OPT.USERINCLUDE'/>
		<param name='PREFIX.RESPONSEFILE'/>
		<param name='BROWSETOOL'/>
		<param name='BROWSEFLAGS'/>
		<param name='CC'/>
		<param name='CDEFS'/>
		<param name='CFLAGS'/>
		<param name='CFLAGS.DEFAULT.WARNLEVEL'/>
		<param name='CFLAGS.LIB'/>
	</interface>

	<interface name='msvctools.exe' extends='msvctools.toolchain' flm='msvctools.flm'>
		<param name='BASE_TYPE' default='exe'/>
		<param name='BASE_MACRO' default='__EXE__'/>
		<param name='LD'/>
		<param name='LFLAGS'/>
		<param name='OPT.IMPLIB'/>
		<param name='CFLAGS.ADD' default=''/>
		<param name='SUBSYSTEM' default='console'/>
	</interface>

	<interface name='msvctools.lib' extends='msvctools.toolchain' flm='msvctools.flm'>
		<param name='BASE_TYPE' default='staticlib'/>
		<param name='BASE_MACRO' default=''/>
		<param name='AR'/>
		<param name='ARFLAGS'/>
		<param name='CFLAGS.ADD' default='_MT'/>
		<param name='SUBSYSTEM' default='windows'/>
	</interface>

</build>

=== SymbianSource/oss.FCL.sftools.dev.build/sbsv2/raptor/test/custom_options/dfsconfig/.sbs_init.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<build xmlns="http://symbian.com/xml/build"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://symbian.com/xml/build build/2_0.xsd">

	<var name="make_changes">
	<set name="bitmap.selector.iface" value="\.(bitmap|extension|mifconv|akniconinterfaces|removegtfiles|skingenerator|cryptoprep|builder|help_files|version_update)$"/>
		<set name="resource.selector.iface" value="\.(resource|extension|mif2cdlindex|nativejava|genericcopy)$"/>
   <set name="default.selector.iface" value="\.(?!export$|bitmap$|resource$|mifconv$|mif2cdlindex$|nativejava$|akniconinterfaces$|removegtfiles$|genericcopy$|skingenerator$|cryptoprep$|builder$|help_files$|version_update$).*$"/>
    <!-- 4.5 min -->
	  <set name='TALON_TIMEOUT' value='540000'/> 
  </var>

	<!-- emake -->
	<alias name="emake" meaning="emake_engine.make_changes"/>  

	<!-- gnu make -->
	<alias name="make" meaning="make_engine.make_changes"/>
	<alias name="dfstestmake" meaning="make_engine.make_changes"/>

	
</build>

=== SymbianSource/oss.FCL.sftools.dev.build/sbsv2/raptor/lib/config/gcc_x86.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<build xmlns="http://symbian.com/xml/build" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://symbian.com/xml/build ../../schema/build/2_0.xsd">
	<!-- build variant for GCC x86 toolchains -->
	<var name="gccx86_base">
		<set name="TOOLCHAIN" value="GCC"/>
		<set name="PLATMACROS.TOOLCHAIN" value="X86GCC GCC32"/>
		
		<set name="TRADITIONAL_PLATFORM" value="X86"/>
		<set name="VARIANTPLATFORM" value="x86"/>

		<!-- toolchain tools -->
		<set name="GCCX86AR" value="$(GCCX86BIN)/ar$(DOTEXE)"/>
		<set name="GCCX86ASM" value="$(GCCX86BIN)/as$(DOTEXE)"/>
		<set name="GCCX86CC" value="$(GCCX86BIN)/g++$(DOTEXE)"/>
		<set name="GCCX86LD" value="$(GCCX86BIN)/g++$(DOTEXE)"/>
		<set name="GCCX86DLLTOOL" value="$(GCCX86BIN)/dlltool$(DOTEXE)"/>
		<set name="FROMELF" value="$(GCCX86BIN)/readelf$(DOTEXE)"/>

		<set name="CC" value="$(GCCX86CC)"/>
		<set name="LD" value="$(GCCX86LD)"/>
		<set name="ASM" value="$(GCCX86ASM)"/>
		<set name="AR" value="$(GCCX86AR)"/>
		<set name="DLLTOOL" value="$(GCCX86DLLTOOL)"/>
		
		<set name="AAPCS_OPTION" value=""/>
		<set name="ARCHIVER_CREATE_OPTION" value="cr"/>
		<set name="ARM_INSTRUCTION_SET" value=""/>
		<set name="ARMLIBS" value=""/>
		<set name="ASM_OUTPUT_OPTION" value="-o"/>
		<set name="ASSEMBLER_LISTING_OPTION" value="-S"/>
		<set name="BPABI_OPTION" value=""/>
		<set name="C_LANG_OPTION" value="-x c -masm=intel"/>
		<set name="CC.NO_UNALIGNED_ACCESS" value=""/>
		<set name="CC.SOFTVFP_MAYBE_VFPV2" value="soft"/>
		<set name="CC.SOFTVFP_MAYBE_VFPV3" value="soft"/>
		<set name="CC_ERRORS_CONTROL_OPTION" value=""/>
		<set name="CC_WARNINGS_CONTROL_OPTION" value="-Wall -Wno-unknown-pragmas"/>
		<set name="CIADEFS" value="__CIA__"/>
		<set name="CODE_SEGMENT_START" value="-Ttext"/>
		<set name="COMMANDFILE_OPTION" value="@"/>
		<set name="COMPILE_ONLY_OPTION" value="-c"/>
		<set name="COMPILER_CIA_FLAGS" value="-O1 -fomit-frame-pointer"/>
		<set name="COMPILER_FPU_OPTION" value=""/>		
		<set name="COMPILER_INTERWORK_DEFINES" value=""/>
		<set name="COMPILER_SYSTEM_INCLUDE_OPTION" value="-I"/>
		<set name="COMPILER_THUMB_DEFINES" value=""/>
		<set name="CPP_LANG_OPTION" value="-x c++ -masm=intel -fno-rtti -fno-exceptions -fcheck-new"/>
		<set name="DATA_SEGMENT_START" value="$(SPLIT_OPTION) $(RW_BASE_OPTION)"/>
		<set name="DEBUG_OPTIMISATION" value="-O0"/>
		<set name="DEBUGINFO_OPTIMISATION" value=""/>
		<set name="DEPEND_OPTION" value="-MD -MF"/>
		<set name="ENUM_OPTION" value=""/>
		<set name="EXCEPTIONS" value=""/>
		<set name="EXPORT_VTBL_OPTION" value=""/>
		<set name="EXTRA_CC_OPTION" value=""/>
		<set name="EXTRA_LD_OPTION" value=""/>
		<set name="FPMODE_OPTION" value=""/>
		<set name="HEADER_FILES_CONTROL_OPTION" value=""/>
		<set name="INSTRUCTION_SET" value=""/>
		<set name="KERNEL_STATIC_RUNTIME_LIB" value=""/>
		<set name="LD_ERRORS_CONTROL_OPTION" value=""/>
		<set name="LD_WARNINGS_CONTROL_OPTION" value=""/>
		<set name="LIBPATH" value=""/>
		<set name="LIBRARY" value=""/>
		<set name="LICENSERETRY_OPTION" value=""/>
		<set name="LINKER_ADD_STATIC_RUNTIME" value="1"/>
		<set name="LINKER_DEBUG_OPTION" value=""/>
		<set name="LINKER_DEFAULT_LIB_PATHS" value=""/>
		<set name="LINKER_DEFAULT_LIBS" value=""/>
		<set name="LINKER_ENTRY_OPTION" value="-Wl,--entry"/>
		<set name="LINKER_GROUP_END_OPTION" value="--end-group"/>
		<set name="LINKER_GROUP_START_OPTION" value="--start-group"/>
		<set name="LINKER_MISC_FLAGS" value="-nostdlib"/>
		<set name="LINKER_NODEBUG_OPTION" value = ""/>
		<set name="LINKER_SCRIPT_FILE_OPTION" value="-T"/>
		<set name="LINKER_SYMBOLS_FILE_OPTION" value="-Wl,-Map"/>
		<set name="LINKER_SYMBOLS_OPTION" value=""/>
		<set name="LISTING_OPTION" value="-S"/>
		<set name="NEED_ENTRYPOINT_LIBRARY" value="" />
		<set name="NEED_ENTRYPOINT_LIBRARY" value=""/>
		<set name="NO_EXCEPTIONS" value="-fno-exceptions"/>
		<set name="NO_UNALIGNED_ACCESS" value="$(CC.NO_UNALIGNED_ACCESS)"/>
		<set name="OWN_LIBRARY_OPTION" value=""/>
		<set name="PL.SOFTVFP_MAYBE_VFPV2" value="softvfp"/>
		<set name="PL.SOFTVFP_MAYBE_VFPV3" value="softvfp"/>
		<set name="PREINCLUDE" value="$(EPOCINCLUDE)/gcc.h"/>
		<set name="PREINCLUDE_OPTION" value="-include"/>
		<set name="PREPROCESSOR_OPTION" value="-E"/>
		<set name="REL_OPTIMISATION" value="-O2"/>
		<set name="RELOCATABLE_IMAGE_OPTION" value=""/>
		<set name="RUNTIME_SYMBOL_VISIBILITY_OPTION" value=""/>
		<set name="RVCTBIN" value="" />
		<set name="RVCTINC" value="" />
		<set name="RVCTLIB" value=""/>
		<set name="RW_BASE" value=""/>
		<set name="RW_BASE_OPTION" value=""/>
		<set name="SHARED_OBJECT_OPTION" value="-Wl,--dll"/>
		<set name="SID" value=""/>
		<set name="SO_NAME_OPTION" value=""/>
		<set name="SPLIT_OPTION" value=""/>
		<set name="STATIC_LIBS_LIST" value=""/>
		<set name="STATIC_LIBS_PATH" value="" />
		<set name="STDCPP_INCLUDE" value="$(EPOCINCLUDE)/stdapis"/>
		<set name="STDLIB_OPTION" value=""/>
		<set name="SUPPORTS_ABIV1_IMPLIBS" value=""/>	
		<set name="SYMBIAN_LD_MESSAGE_OPTION" value="$(LD_WARNINGS_CONTROL_OPTION) $(LD_ERRORS_CONTROL_OPTION)"/>
		<set name="SYMVER_OPTION" value=""/>
		<set name="TARGET_RELOCATION_OPTION" value="--target1-rel" />
		<set name="TEMP_FILES_OPTION" value="-pipe"/>
		<set name="THUMB_INSTRUCTION_SET" value=""/>
		<set name="TRANSFORM_CIA" value=""/>		
		<set name="UNDEFINED_SYMBOL_REF_OPTION" value="-u"/>
		<set name="UNRESOLVED_SYMBOL_REF_OPTION" value=""/>
		<set name="USER_LIBS_PATH_OPTION" value="--userlibpath"/>
		<set name="USER_STATIC_RUNTIME_LIB" value=""/>
		<set name="USER_STATIC_RUNTIME_LIB_NESTED_EXCEPTIONS" value=""/>
		<set name="USERINCLUDE" value=""/>
		<set name="VFE_OPTION" value=""/>

		<append name="CDEFS" value="__X86GCC__ __GCC32__"/>
	</var>
</build>

=== SymbianSource/oss.FCL.sftools.dev.build/sbsv2/raptor/lib/config/gcc.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<build xmlns="http://symbian.com/xml/build" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://symbian.com/xml/build ../../schema/build/2_0.xsd">
	<!-- build variants for GCC toolchains -->
	<var name="tools2_base" extends="root">
		<varRef ref="default.interfaces"/>
		<varRef ref="default.locations"/>
		
		<!-- toolchain tools -->
		<env name='RANLIB' default='$(GCCPREFIX)ranlib$(DOTEXE)' type='tool'/>
		<env name='GCC' default='$(GCCPREFIX)g++$(DOTEXE)' type='tool'/>
		<env name='AR' default='$(GCCPREFIX)ar$(DOTEXE)' type='tool'/>
		
		<set name='COMPILER' value='$(GCC) -c' type='tool' versionCommand='$(GCC) -v' versionResult='gcc version (3.[456])|(4.[0-9])'/>
		<set name='LINKER' value='$(GCC)'/>

		<!-- tools and scripts -->
		<env name='JAVATC' default='$(JAVA_HOME)/bin/java' type='tool'/> <!-- Java used by Trace Compiler -->
		<env name='JAVA_HOME' default='' type='path'/>		

		<!-- targettypes -->
		<set name="TARGET_TYPES" value="exe lib"/>

		<!-- interfaces -->
		<append name="INTERFACE_TYPES" value="$(TARGET_TYPES)"/>

		<set name="INTERFACE.exe" value="Tools.exe"/>
		<set name="INTERFACE.lib" value="Tools.lib"/>

		<!-- link to bld.inf and mmp platform names -->
		<set name='TRADITIONAL_PLATFORM' value='TOOLS2'/>

		<set name='CFLAGS' value='-fdefer-pop -fmerge-constants -fthread-jumps -floop-optimize -fif-conversion -fif-conversion2 -fguess-branch-probability -fcprop-registers -foptimize-sibling-calls -fstrength-reduce -fcse-follow-jumps -fcse-skip-blocks -frerun-cse-after-loop -frerun-loop-opt -fgcse -fgcse-lm -fgcse-sm -fgcse-las -fdelete-null-pointer-checks -fexpensive-optimizations -fregmove -fschedule-insns -fschedule-insns2 -fsched-interblock -fsched-spec -fcaller-saves -fpeephole2 -freorder-blocks -freorder-functions -fstrict-aliasing -funit-at-a-time -falign-functions -falign-jumps -falign-loops -falign-labels -fcrossjumping -pipe -Wall -Wno-ctor-dtor-privacy -Wno-unknown-pragmas -m32'/>
		
		<set name='VARIANTPLATFORM' value='tools2'/>

		<!-- COMPILER_PATH can be set to tell gcc where to find as.exe (sometimes it doesn't and a build step fails). -->
		<set name='COMPILER_PATH.WIN32' value='$(SBS_HOME)/win32/mingw/bin'/>
		<set name='COMPILER_PATH.LINUX' value=''/>

		<set name='CFLAGS.WIN32' value=''/>

		<!-- macro definitions set by mmps etc -->
		<set name='CDEFS' value='$(MMPDEFS)'/>
		<set name='CDEFS.DEFAULT' value='__SYMBIAN32__ __TOOLS__ __TOOLS2__ __EXE__ __SUPPORT_CPP_EXCEPTIONS__ __PRODUCT_INCLUDE__="$(PRODUCT_INCLUDE)"'/>
		<set name='CDEFS.WIN32' value='$(CDEFS.DEFAULT) _WIN32 WIN32 _WINDOWS __TOOLS2_WINDOWS__'/>
		<set name='CDEFS.LINUX' value='$(CDEFS.DEFAULT) __LINUX__ __TOOLS2_LINUX__'/>

		<set name='PREINCLUDE' value='$(EPOCINCLUDE)/gcc_mingw/gcc_mingw_3_4_2.h'/>

		<set name='OPT.D' value='-D'/>
		<set name='OPT.L' value='-L'/>
		<set name='OPT.l' value='-l'/>
		<set name='OPT.O' value='-o '/>
		<set name='OPT.PREINCLUDE' value='-include '/>
		<set name='OPT.SYSTEMINCLUDE' value='-isystem '/>
		<set name='OPT.USERINCLUDE' value='-I '/>

		<!-- always use stlport headers -->
		<env name='SBS_STLPORTINCDIR' default='$(EPOCINCLUDE)/tools/stlport' type='path'/>
		<set name='SYSTEMINCLUDE' value='$(SBS_STLPORTINCDIR)'/>

		<set name='LFLAGS' value=''/>
		<set name='STATICLIBRARY' value=''/>
		<set name='LIBS' value=''/>
		<set name='LIBS.WIN32' value='$(LIBS)'/>
		<set name='LIBS.LINUX' value='$(LIBS) pthread'/>

		<set name='PLATMACROS.WINDOWS' value='GCC32 TOOLS2 TOOLS2_WINDOWS'/>
		<set name='PLATMACROS.LINUX' value='GCC32 TOOLS2 TOOLS2_LINUX'/>

		<set name='ARCHIVER' value='$(AR)'/>
		<set name='AFLAGS' value='cr'/>

		<set name='MMPDEFS' value=''/>
		<set name='TARGET' value=''/>
		<set name='TARGETTYPE' value=''/>
		<set name='BLDINF_OUTPUTPATH' value='$(SBS_BUILD_DIR)'/>

		<set name='OUTPUTPATH' value='$(SBS_BUILD_DIR)'/>
		<env name='SBS_STLPORTBINDIR' default='$(EPOCROOT)/epoc32/release/tools2' host='win.*' type='path'/>
		<env name='SBS_STLPORTBINDIR' default='$(EPOCROOT)/epoc32/release/tools2/$(HOSTPLATFORM32_DIR)' host='lin.*' type='path'/>
		<set name='STLPORTBINDIR' value='$(SBS_STLPORTBINDIR)'/>
		<set name='STLPORTLIBRARY' value='stlport.5.1'/>
		<set name='RELEASEPATH' value='$(EPOCROOT)/epoc32/release/tools2' host='win.*' type='path'/>
		<!-- Tools are 32-bit at the moment, so use the 32-bit directory -->
		<set name='RELEASEPATH' value='$(EPOCROOT)/epoc32/release/tools2/$(HOSTPLATFORM32_DIR)' host='lin.*' type='path'/>
	</var>

	<var name="t_deb">
		<set name='TOOLSPATH' value=''/> <!-- do not install -->
		<set name='VARIANTTYPE' value='deb'/>

		<append name='CFLAGS' value='-g'/>
		<append name='CDEFS' value='_DEBUG'/>
		<append name='RELEASEPATH' value='/deb' separator=''/>
		<append name='STLPORTBINDIR' value='/deb' separator=''/>		
	</var>
	<alias name="tools2_deb" meaning="tools2_base.t_deb"/>
	
	<var name="t_rel">
		<set name='TOOLSPATH' value='$(EPOCROOT)/epoc32/tools'/> <!-- install -->
		<set name='VARIANTTYPE' value='rel'/>

		<append name='CFLAGS' value='-s'/>
		<append name='CDEFS' value='NDEBUG'/>
		<append name='RELEASEPATH' value='/rel' separator=''/>
		<append name='STLPORTBINDIR' value='/rel' separator=''/>		
	</var>
	<alias name="tools2_rel" meaning="tools2_base.t_rel"/>
	
	<group name="tools2">
		<aliasRef ref='tools2_rel'/>
		<aliasRef ref='tools2_deb'/>
	</group>

</build>

=== SymbianSource/oss.FCL.sftools.dev.build/sbsv2/raptor/test/smoke_suite/test_resources/tracecompiler/multiple_variants/variants.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<build xmlns="http://symbian.com/xml/build" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://symbian.com/xml/build build/2_0.xsd">

	<var name="feature_variant_base">
		<set name='USE_TRACE_COMPILER' value='1' />       
		<set name='FEATURELISTFILES' value='$(SBS_HOME)/test/smoke_suite/test_resources/tracecompiler/multiple_variants/list.txt'/>
		<env name='JAVA_HOME' default='C:/APPS/jdk_1.6.0_11' type='path'/>
		<env name='SBS_JAVATC' default='$(JAVA_HOME)/bin/java' type='tool' versionCommand='$(SBS_JAVATC) -version' versionResult='version \"1\.[5-9]' />
	</var>

	<var name="phone1" extends="feature_variant_base">
		<set name='FEATUREVARIANTNAME' value='.phone1'/>
		<set name='VARIANT_HRH' value='$(SBS_HOME)/test/smoke_suite/test_resources/tracecompiler/multiple_variants/hrh/var1.hrh'/> 
	</var>

	<var name="phone2" extends="feature_variant_base">
		<set name='FEATUREVARIANTNAME' value='.phone2'/> 
		<set name='VARIANT_HRH' value='$(SBS_HOME)/test/smoke_suite/test_resources/tracecompiler/multiple_variants/hrh/var2.hrh'/> 
	</var>

	<var name="phone3" extends="feature_variant_base">
		<set name='FEATUREVARIANTNAME' value='.phone3'/> 
		<set name='VARIANT_HRH' value='$(SBS_HOME)/test/smoke_suite/test_resources/tracecompiler/multiple_variants/hrh/var3.hrh'/> 
	</var>

</build>

=== SymbianSource/oss.FCL.sftools.dev.build/sbsv2/raptor/lib/config/root.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<build xmlns="http://symbian.com/xml/build" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://symbian.com/xml/build ../../schema/build/2_0.xsd">

	<!-- 
	
	The root variant is extended by all buildable variants.
	
	It contains references to variants which have defaults here but which
	can be overridden to effectively apply a global change for all builds. 
	
	-->

	<var name="root">
		<env name='FLMDEBUG' default=''/>	
	
		<varRef ref="root.places"/>
		<varRef ref="root.properties"/>
		
		<!-- redefine this to make changes to the root variant -->
		<varRef ref="root.changes"/>
	</var>

	<!-- Common folders and files -->
	<var name="root.places">
		<env name='EPOCROOT' default='/' type='path'/>
		<env name='SBS_EPOCTOOLS' default='$(EPOCROOT)/epoc32/tools' type='path'/>
		
		<set name='EPOCINCLUDE' value='$(EPOCROOT)/epoc32/include'/>
		<set name='EPOCTOOLS' value='$(SBS_EPOCTOOLS)'/>

		<!-- Place where intermediate files are built -->
		<env name='SBS_BUILD_DIR' default='$(EPOCROOT)/epoc32/build' type='path'/> 

		<!-- Configuration files and directories -->
		<set name='PRODUCT_INCLUDE' value='$(EPOCINCLUDE)/variant/symbian_os.hrh'/>
		<set name='VARIANT_CFG' value='$(EPOCROOT)/epoc32/tools/variant/variant.cfg'/>
		<set name='MAKEFILE_TEMPLATES' value='$(EPOCROOT)/epoc32/tools/makefile_templates'/>
		<set name='FLM_EXPORT_DIR' value='$(MAKEFILE_TEMPLATES)'/>
	</var>
	
	<!-- Things which are properties of different OS versions rather than
		 properties of Raptor itself. The values here are for TB92sf and
		 may be completely redefined for other OS versions or modified
		 slightly by redefining the root.changes variant. -->
	<var name="root.properties">
		<set name='POSTLINKER_SUPPORTS_WDP' value='1'/>
		<set name='SUPPORTS_STDCPP_NEWLIB' value='1'/>
		<set name="RVCT_PRE_INCLUDE" value="$(EPOCINCLUDE)/rvct/rvct.h"/>
		<set name="SUPPORTS_ABIV1_IMPLIBS" value=''/>
	</var>
	
	<!-- Placeholder for the root.changes variant. This will typically be
	     redefined inside a .xml file in the $(EPOCROOT)/epoc32/sbs_config
	     folder or a folder added with the configpath option. -->
	<var name="root.changes"/>
	
</build>
