=== SymbianSource/oss.FCL.sftools.dev.build/sbsv2/raptor/schema/build/2_0.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://symbian.com/xml/build" targetNamespace="http://symbian.com/xml/build" elementFormDefault="qualified">
	<xsd:annotation>
		<xsd:documentation xml:lang="en">
			Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
			All rights reserved.
			This component and the accompanying materials are made available
			under the terms of the License "Eclipse Public License v1.0"
			which accompanies this distribution, and is available
			at the URL "http://www.eclipse.org/legal/epl-v10.html".

			Initial Contributors:
			Nokia Corporation - initial contribution.

			Contributors:

			Description:

		</xsd:documentation>
	</xsd:annotation>
	<xsd:element name="build">
		<xsd:complexType>
			<xsd:sequence maxOccurs="unbounded">
				<xsd:element ref="var" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="alias" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="group" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="interface" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="var">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:sequence minOccurs="0">
					<xsd:element ref="varRef" minOccurs="0" maxOccurs="unbounded"/>
				</xsd:sequence>
				<xsd:sequence maxOccurs="unbounded">
					<xsd:element name="env" minOccurs="0" maxOccurs="unbounded">
						<xsd:complexType>
							<xsd:attribute name="name" type="xsd:string" use="required"/>
							<xsd:attribute name="default" type="xsd:string" use="optional"/>
							<xsd:attribute name="type" type="xsd:string"/>
							<xsd:attribute name="versionCommand" type="xsd:string"/>
							<xsd:attribute name="versionResult" type="xsd:string"/>
						</xsd:complexType>
					</xsd:element>
					<xsd:element name="set" minOccurs="0" maxOccurs="unbounded">
						<xsd:complexType>
							<xsd:attribute name="name" type="xsd:string" use="required"/>
							<xsd:attribute name="value" type="xsd:string" use="required"/>
							<xsd:attribute name="type" type="xsd:string"/>
							<xsd:attribute name="versionCommand" type="xsd:string"/>
							<xsd:attribute name="versionResult" type="xsd:string"/>
							<xsd:attribute name="host" type="xsd:string"/>
						</xsd:complexType>
					</xsd:element>
					<xsd:element name="append" minOccurs="0" maxOccurs="unbounded">
						<xsd:complexType>
							<xsd:attribute name="name" type="xsd:string" use="required"/>
							<xsd:attribute name="value" type="xsd:string" use="required"/>
							<xsd:attribute name="separator" type="xsd:string"/>
						</xsd:complexType>
					</xsd:element>
					<xsd:element name="prepend" minOccurs="0" maxOccurs="unbounded">
						<xsd:complexType>
							<xsd:attribute name="name" type="xsd:string" use="required"/>
							<xsd:attribute name="value" type="xsd:string" use="required"/>
							<xsd:attribute name="separator" type="xsd:string"/>
						</xsd:complexType>
					</xsd:element>
				</xsd:sequence>
			</xsd:sequence>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="extends" type="xsd:string"/>
			<xsd:attribute name="host" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="alias">
		<xsd:complexType>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="meaning" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="group">
		<xsd:complexType>
			<xsd:sequence maxOccurs="unbounded">
				<xsd:element ref="varRef" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="aliasRef" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="groupRef" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="name" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="varRef">
		<xsd:complexType>
			<xsd:attribute name="ref" type="xsd:string" use="required"/>
			<xsd:attribute name="mod" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="aliasRef">
		<xsd:complexType>
			<xsd:attribute name="ref" type="xsd:string" use="required"/>
			<xsd:attribute name="mod" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="groupRef">
		<xsd:complexType>
			<xsd:attribute name="ref" type="xsd:string" use="required"/>
			<xsd:attribute name="mod" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="interface">
		<xsd:complexType>
			<xsd:sequence minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="param" minOccurs="0" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:attribute name="name" type="xsd:string" use="required"/>
						<xsd:attribute name="default" type="xsd:string"/>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="paramgroup" minOccurs="0" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:attribute name="pattern" type="xsd:string" use="required"/>
						<xsd:attribute name="default" type="xsd:string"/>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="extends" type="xsd:string"/>
			<xsd:attribute name="abstract" type="xsd:boolean"/>
			<xsd:attribute name="flm" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== SymbianSource/oss.FCL.sftools.dev.build/sbsv2/raptor/test/unit_suite/data/sbs_init.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<build xmlns="http://symbian.com/xml/build"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://symbian.com/xml/build build/2_0.xsd">

  <!-- defaults for Raptor -->

  <var name="defaults.init">
    <!-- environment variables used in this configuration -->
    <env name="EPOCROOT" default="/" type="path"/>

    <!-- default parameter settings -->

    <!-- Make command parameter file -->
    <set name="makeEngine" value="make"/>

    <!-- Location of the highest level makefile -->
    <set name="topMakefile" value="$(EPOCROOT)/epoc32/build/Makefile"/>

    <!-- Name of the build logging file -->
    <set name="logFileName" value="$(EPOCROOT)/epoc32/build/Makefile.%TIME.log"/>

    <!-- Default build configuration name -->
    <set name="defaultConfig" value="default"/>

    <!-- Names of standard build files -->
    <set name="buildInformation" value="bld.inf"/>
    <set name="systemDefinition" value="System_Definition.xml"/>

    <!-- Standard directories -->
    <set name="systemConfig" value="lib/config"/>
    <set name="systemFLM" value="lib/flm"/>
    <set name="systemPlugins" value="python/plugins"/>
    <set name="systemDefinitionBase" value="."/>

    <!-- Do not print any information messages? -->
    <set name="quiet" value="false"/>

    <!-- How many jobs to run in parallel? (for make -j) -->
    <set name="jobs" value="4"/>

    <!-- How many attempts to run a job before recording an error?
    This is useful for builds that can have transient failures. -->
    <set name="tries" value="1"/>

    <!-- Carry on trying to build even if some commands fail? -->
    <set name="keepGoing" value="false"/>

    <!-- Can command line options override values in this file? -->
    <set name="allowCommandLineOverrides" value="true"/>

    <!-- Do we use a bld.inf or System_Definition.xml if both are in the CWD -->
    <set name="preferBuildInfoToSystemDefinition" value="false"/>

    <!-- Always use ignore OS detection? -->
    <set name="ignoreOsDetection" value="false"/>

    <!-- Always use a specific list of filters -->
    <set name="filterList" value="FilterTerminal,FilterLogfile"/>

  </var>

</build>

=== SymbianSource/oss.FCL.sftools.dev.build/sbsv2/raptor/test/smoke_suite/test_resources/tracecompiler/variant_source/use_tc.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<build xmlns="http://symbian.com/xml/build" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://symbian.com/xml/build build/2_0.xsd">
	<!-- test trace compiler -->
	<var name="tc_var_base">
		<set name='USE_TRACE_COMPILER' value='1' />
		<env name='JAVA_HOME' default='' type='path'/>
		<env name='SBS_JAVATC' default='$(JAVA_HOME)/bin/java' type='tool' versionCommand='$(SBS_JAVATC) -version' versionResult='version \"1\.[5-9]' />
	</var>
	<var name="tc_var1" extends="tc_var_base">
		<prepend name='SYSTEMINCLUDE' value='$(SBS_HOME)/test/smoke_suite/test_resources/tracecompiler/variant_source/var1' />
	</var>
	<var name="tc_var2" extends="tc_var_base">
		<prepend name='SYSTEMINCLUDE' value='$(SBS_HOME)/test/smoke_suite/test_resources/tracecompiler/variant_source/var2' />
	</var>

</build>

=== SymbianSource/oss.FCL.sftools.dev.build/sbsv2/raptor/test/config/default.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<build xmlns="http://symbian.com/xml/build"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://symbian.com/xml/build build/2_0.xsd">

    <!-- The build configurations built by default -->

	<var name="default">
		<set name="OVER" value="default"/>
		<varRef ref="A"/>
		<varRef ref="B"/>
	</var>

	<var name="baseA">
		<set name="BASE" value="baseA"/>
		<set name="OVER" value="baseA"/>
	</var>

	<var name="A" extends="baseA">
		<set name="OVER" value="A"/>
		<varRef ref="A2"/>
		<varRef ref="A3"/>
	</var>

	<var name="baseB">
		<set name="BASE" value="baseB"/>
		<set name="OVER" value="baseB"/>
	</var>

	<var name="B" extends="baseB">
		<set name="OVER" value="B"/>
		<varRef ref="B2"/>
		<varRef ref="B3"/>
	</var>

	<var name="A2">
		<set name="OVER" value="A2"/>
	</var>

	<var name="A3">
		<set name="OVER" value="A3"/>
	</var>

	<var name="B2">
		<set name="OVER" value="B2"/>
	</var>

	<var name="B3">
		<set name="OVER" value="B3"/>
	</var>

</build>

=== SymbianSource/oss.FCL.sftools.dev.build/sbsv2/raptor/test/config/api.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<build xmlns="http://symbian.com/xml/build"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://symbian.com/xml/build build/2_0.xsd">

	<!-- test data for raptor_api_unit -->

	<alias meaning="a" name="alias_A"/>
	<alias meaning="a.b" name="alias_B"/>
	<alias meaning="a.b.c" name="alias_C" type="O"/>
	<alias meaning="a.b.c.d" name="alias_D" type="X"/>
 
 	<var name="product_A" type="product"/>
 	<var name="product_B"/>
 	<var name="product_C" type="product"/>
 	<var name="product_D"/>
 	
 	<var name="buildme">
 		<set name="RELEASEPATH" value="/home/raptor"/>
 		<set name="VARIANTPLATFORM" value="foo"/>
 		<set name="VARIANTTYPE" value="bar"/>
 	</var>
 	
 	<var name="foo"/>
 	<var name="bar"/>
 	
 	<alias name="s1" meaning="buildme.foo"/>
 	<alias name="s2" meaning="buildme.foo.bar"/>
 	
</build>

=== SymbianSource/oss.FCL.sftools.dev.build/sbsv2/raptor/lib/config/interfaces.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<build xmlns="http://symbian.com/xml/build" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://symbian.com/xml/build ../../schema/build/2_0.xsd">
	<!-- The standard interfaces used by most configurations. -->

	<var name="default.interfaces">
		<!-- interfaces corresponding to target types -->

		<set name="INTERFACE_TYPES" value="exe stdexe ext_makefile dll stddll lib stdlib export extension ani plugin plugin3 textnotifier2 implib var var2 exexp kexe kdll kext klib pdll ldd pdd pdl fsy resource none stringtable bitmap"/>
		<set name="INTERFACE.exe" value="Symbian.exe"/>
		<set name="INTERFACE.stdexe" value="Symbian.stdexe"/>
		<set name="INTERFACE.stddll" value="Symbian.stddll"/>
		<set name="INTERFACE.stdlib" value="Symbian.stdlib"/>
		<set name="INTERFACE.dll" value="Symbian.dll"/>
		<set name="INTERFACE.pdll" value="Symbian.pdll"/>
		<set name="INTERFACE.lib" value="Symbian.lib"/>
		<set name="INTERFACE.ani" value="Symbian.ani"/>
		<set name="INTERFACE.plugin" value="Symbian.plugin"/>
		<set name="INTERFACE.plugin3" value="Symbian.plugin3"/>
		<set name="INTERFACE.textnotifier2" value="Symbian.textnotifier2"/>
		<set name="INTERFACE.implib" value="Symbian.implib"/>
		<set name="INTERFACE.var" value="Symbian.var"/>
		<set name="INTERFACE.var2" value="Symbian.var2"/>
		<set name="INTERFACE.exexp" value="Symbian.exexp"/>
		<set name="INTERFACE.kexe" value="Symbian.kexe"/>
		<set name="INTERFACE.kdll" value="Symbian.kdll"/>
		<set name="INTERFACE.kext" value="Symbian.kext"/>
		<set name="INTERFACE.klib" value="Symbian.klib"/>
		<set name="INTERFACE.ldd" value="Symbian.ldd"/>
		<set name="INTERFACE.pdd" value="Symbian.pdd"/>
		<set name="INTERFACE.pdl" value="Symbian.pdl"/>
		<set name="INTERFACE.fsy" value="Symbian.fsy"/>
		<set name="INTERFACE.none" value="Symbian.none"/>
		<set name="INTERFACE.ext_makefile" value="base.ext_makefile"/>
		<set name="INTERFACE.extension" value="base.extension"/>
		<set name="INTERFACE.export" value="base.export"/>
		<set name="INTERFACE.resource" value="base.resource"/>
		<set name="INTERFACE.stringtable" value="base.stringtable"/>
		<set name="INTERFACE.bitmap" value="base.bitmap"/>

		<!-- per-configuration default interfaces -->
		<set name="INTERFACE.config" value="Symbian.config.default"/>
	</var>

</build>
